spring:
  application:
    name: order-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true # ðŸ”¥ ì´ ì„¤ì •ì´ ì—†ìœ¼ë©´ fallbackì´ ë™ìž‘í•˜ì§€ ì•ŠìŒ

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082

management:
  endpoints:
    web:
    exposure:
      include: '*'

resilience4j:
  circuitbreaker:
    instances:
      productClient: # ë°˜ë“œì‹œ @FeignClient ì˜ nameê³¼ ì¼ì¹˜
        registerHealthIndicator: true # actuatorì— ë…¸ì¶œ
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10 # 10ê°œì˜ ìš”ì²­ ê¸°ì¤€
        minimumNumberOfCalls: 5 # ìµœì†Œ ìš”ì²­ ìˆ˜ ë„ë‹¬í•´ì•¼ ìƒíƒœ í‰ê°€ ì‹œìž‘
        failureRateThreshold: 50 # 50% ì´ìƒ ì‹¤íŒ¨ ì‹œ OPEN ìƒíƒœë¡œ ì „í™˜
        waitDurationInOpenState: 5s # OPEN -> HALF_OPEN ëŒ€ê¸° ì‹œê°„
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          #- java.util.concurrent.TimeoutException
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
